name: book_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  image_picker: ^1.1.1
  jwt_decoder: ^2.0.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
